### ISSUE TITLE
motorola_umts_spyder build failed.

### ISSUE THREAD

**Issue by lkthomas** [ResurrectionRemix/platform_manifest#44]
Which would you like? [aosp_arm-eng] cm_umts_spyder-userdebug
build/core/product_config.mk:239: *** _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]: "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does not exist.  Stop.
Device umts_spyder not found. Attempting to retrieve device repository from CyanogenMod Github (http://github.com/CyanogenMod).
Found repository: android_device_motorola_umts_spyder
Default revision: cm-12.1
Checking branch info
CyanogenMod/android_device_motorola_umts_spyder already exists
Syncing repository to retrieve project.
Fetching project CyanogenMod/android_device_motorola_umts_spyder
Fetching projects: 100% (1/1), done.  

Repository synced!
Looking for dependencies
Done
build/core/product_config.mk:239: *** _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]: "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does not exist.  Stop.

** Don't have a product spec for: 'cm_umts_spyder'
** Do you have the right repo manifest?

  Starting compilation of Resurrection Remix...

Enter the number of threads you want to use for compilation
If you unsure on what to select, enter 0
0
make: Entering directory `/local/thomas_android_source/ResurrectionRemix/source'
build/core/product_config.mk:239: *** _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]: "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does not exist.  Stop.
make: Leaving directory `/local/thomas_android_source/ResurrectionRemix/source'

#### make failed to build some targets  ####

real	0m0.240s
user	0m0.206s
sys	0m0.042s

Total time elapsed: 0 minutes (47.405361633 seconds)

**Comment by akhilnarang** [comment]
So add those blobs

**Comment by lkthomas** [comment]
Sorry, how? I am new to this.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Akhil NarangSent: Wednesday, 4 November, 2015 5:41 PMTo: ResurrectionRemix/platform_manifestReply To: ResurrectionRemix/platform_manifestCc: lkthomasSubject: Re: [platform_manifest] motorola_umts_spyder build failed. (#44)So add those blobs
On Nov 4, 2015 1:35 PM, "lkthomas" <notifications@github.com> wrote:

> Which would you like? [aosp_arm-eng] cm_umts_spyder-userdebug
> build/core/product_config.mk:239: ***
> _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]:
> "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does
> not exist. Stop.
> Device umts_spyder not found. Attempting to retrieve device repository
> from CyanogenMod Github (http://github.com/CyanogenMod
> <https://github.com/CyanogenMod>).
> Found repository: android_device_motorola_umts_spyder
> Default revision: cm-12.1
> Checking branch info
> CyanogenMod/android_device_motorola_umts_spyder already exists
> Syncing repository to retrieve project.
> Fetching project CyanogenMod/android_device_motorola_umts_spyder
> Fetching projects: 100% (1/1), done.
>
> Repository synced!
> Looking for dependencies
> Done
> build/core/product_config.mk:239: ***
> _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]:
> "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does
> not exist. Stop.
>
> ** Don't have a product spec for: 'cm_umts_spyder'
> ** Do you have the right repo manifest?
>
> Starting compilation of Resurrection Remix...
>
> Enter the number of threads you want to use for compilation
> If you unsure on what to select, enter 0
> 0
> make: Entering directory
> /local/thomas_android_source/ResurrectionRemix/source'
> build/core/product_config.mk:239: ***
> _nic.PRODUCTS.[[device/motorola/umts_spyder/cm.mk]]:
> "vendor/motorola/omap4-common/omap4-common-imgtec-vendor-blobs.mk" does
> not exist. Stop.
> make: Leaving directory
> /local/thomas_android_source/ResurrectionRemix/source'
> make failed to build some targets
>
> real 0m0.240s
> user 0m0.206s
> sys 0m0.042s
>
> Total time elapsed: 0 minutes (47.405361633 seconds)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ResurrectionRemix/platform_manifest/issues/44>.
>


—Reply to this email directly or view it on GitHub.

**Comment by neildufva** [comment]
Add those blobs where? How?

**Comment by varund7726** [comment]
Learn :) .that's what we have a readme for
