### ISSUE TITLE
Vertical App Drawer / AOSP Launcher

### ISSUE THREAD

**Issue by MoNTE48** [ResurrectionRemix/platform_manifest#57]
I and many others hate Trebuchet, I like the vertical App drawer, in the AOSP 6.0. So I have to use Google Start, and some threads in devices which I build RR using Action Launcher, Nova Launcher, etc.
I propose to return to the RR original AOSP Launcher, or make a fork Trebuchet which AOSP App drawer will default. Thanks guys!

**Comment by MoNTE48** [comment]
@westcripp, ^^

**Comment by varund7726** [comment]
Sorry .we need trebuchet for theming purposes

**Comment by MoNTE48** [comment]
But, you could return the AOSP App Drawer, as it is at the Google Start?

**Comment by akhilnarang** [comment]
You can add for your builds if you want
We will stick with trebuchet

**Comment by MoNTE48** [comment]
You do not want to change Trebuchet? Add to it a new function?

**Comment by akhilnarang** [comment]
Trebuchet works fine
Didn't understand what your issue is
