### ISSUE TITLE
fatal: repository 'https://github.com/arter97/android_prebuilt_ndk/' not found

### ISSUE THREAD

**Issue by lkthomas** [ResurrectionRemix/platform_manifest#60]
fatal: repository 'https://github.com/arter97/android_prebuilt_ndk/' not found
error: Cannot fetch arter97/android_prebuilt_ndk

happen when I do "repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -b optimized-lollipop5.1" and "repo sync -j 16", anyone have idea why?

**Comment by akhilnarang** [comment]
LP branch isn't updated anymore, that repo must've been deleted
remove it using roomservice, and track the aosp/cm one

**Comment by lkthomas** [comment]
Can you give me some exact command? Sorry that I am newbie on this.
