### ISSUE TITLE
Missing Branch

### ISSUE THREAD

**Issue by MSF-Jarvis** [ResurrectionRemix/platform_manifest#62]
Where is the KitKat branch of this ROM??

**Comment by MSF-Jarvis** [comment]
And the lollipop5.1 branch is also not syncing due to fetch errors

**Comment by varund7726** [comment]
Deprecated

**Comment by DroidManPK** [comment]
Please Bring back Kitkat branch. To build for older devices. It's fine even if it's not updated. Just bring it back... Pretty please with cherry on top :)

**Comment by akhilnarang** [comment]
We don't have the repos synced
Incase someone does they can update and push them to github
