### ISSUE TITLE
Guide problem

### ISSUE THREAD

**Issue by gegabit** [ResurrectionRemix/platform_manifest#64]
After step: git clone https://github.com/ResurrectionRemix/platform_manifest.git

Folder dont have setup.sh file.

**Comment by dieli** [comment]
Get the setup.sh and build.sh from lollipop branch, then edit the files and replace lollipop with marshmallow.

**Comment by EpicLPer** [comment]
Can someone please edit and upload this here? This is a bit annoying.

**Comment by EpicLPer** [comment]
Okay, did it myself now but I lack the functions to push to this repository. Here you go anyways :)

[rr_marshmallow_build.zip](https://github.com/ResurrectionRemix/platform_manifest/files/173919/rr_marshmallow_build.zip)

**Comment by Furrydaus** [comment]
Hello @gegabit , @dieli and @EpicLPer ,

We've improved the Script based system and would recommend you upgrade to Marshmallow to take advantage of the scripts. Alternatively, you can modify the setup.sh script in https://github.com/ResurrectionRemix/ResurrectedScripts/blob/marshmallow/setup.sh to reflect lollipop instead.

In line 120, change marshmallow to lollipop
```
repo init -u git://github.com/ResurrectionRemix/platform_manifest.git -b marshmallow
```
```
repo init -u git://github.com/ResurrectionRemix/platform_manifest.git -b lollipop
```

Regards,
Firdaus
