### ISSUE TITLE
Outdated Script

### ISSUE THREAD

**Issue by KillerDroid96** [ResurrectionRemix/platform_manifest#80]
Please update script & instructions for Ubuntu 16.04. 
ex: 
libwxgtk2.8-dev --> libwxgtk3.0-dev

repo has been initialized in /home/user/rr
Fetching projects:  99% (527/532)  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

I spent a day trying yo get Ubuntu 14 to work but it doesn't agree with my laptop at all. 16.04 is smoother, display scaled correctly, skylake optimized, wifi works, and it doesn't get stuck in reboot/shutdown. So I would really like to be able to build on 16.04. I can go in and manually update the automated script but id rather have it done by an experienced dev. This is actually my first ROM build ive been a part of the dev community for around 5 years.

**Comment by varund7726** [comment]
This sync error has nothing related to the scripts .its your internet connection

**Comment by KillerDroid96** [comment]
Yeah I figured out that sync issue. The issue seemed to be with the
libwxgtk2.8-dev and a few others. I've build a ROM before for my Jfltespr
and it failed to boot

**Comment by KillerDroid96** [comment]
The libwxgtk2.8-dev might not matter but I wasn't sure so I thought I'd say
something. Does RR have any devs that could possibly help me when I run
into issues on the build?
