### ISSUE TITLE
Double tap action feature to be implemented for the left (menu) & right (back) buttons

### ISSUE THREAD

**Issue by webmaster33** [ResurrectionRemix/platform_manifest#83]
Implement the following features for the left (menu), middle (home), right (back) buttons:
- tap, 
- double tap, 
- long tap. 
So all 3 features should be available for each button. 

Double tap action for home button feature implemented into Resurrection Remix was really useful, so I would ask to implement it for the left (menu) & right (back) buttons, too. 

These options are available in Settings / Configuration / Button controller.

**Comment by varund7726** [comment]
Why are you opening an issue on github? I have mentioned so many times do not spam github with issues or feature reaquests 
Please use g+ to do so

**Comment by webmaster33** [comment]
Sorry, didn't know the rules. Where should I send the feature request?

**Comment by varund7726** [comment]
No problem .and your feature has just been added to the source
