### ISSUE TITLE
what is device code name for xiaomi mi4c?

### ISSUE THREAD

**Issue by luntik2012** [ResurrectionRemix/platform_manifest#84]
I've tried libra and many others

**Comment by nealgosalia** [comment]
It's libra. Don't open unnecessary issues.

**Comment by luntik2012** [comment]
What is your device code name?
libra
You have chosen to build ResurrectionRemix OS for  libra

Building Resurrection Remix OS now!

build/core/product_config.mk:245: *** Can not locate config makefile for product "cm_libra".  Stop.
Device libra not found. Attempting to retrieve device repository from CyanogenMod Github (http://github.com/CyanogenMod).
Repository for libra not found in the CyanogenMod Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:245: *** Can not locate config makefile for product "cm_libra".  Stop.
build/core/product_config.mk:245: *** Can not locate config makefile for product "cm_libra".  Stop.

** Don't have a product spec for: 'cm_libra'
** Do you have the right repo manifest?

Build failed, check the log at libra-20161211.log
nick@pc:/media/nick/build$

**Comment by nealgosalia** [comment]
This is because the CyanogenMod git doesn't have repos for your device. Which is because libra does not have official CM. Please do some research before trying to build a ROM.

**Comment by luntik2012** [comment]
ok, sorry
