### ISSUE TITLE
Can I use another maintainer's device tree?please give me some guidance.

### ISSUE THREAD

**Issue by kmahyyg** [ResurrectionRemix/platform_manifest#91]
Hello, My device is Xiaomi_RedMi3(ido)
The official maintainer is @WinKarbik in RR and the latest version is still 5.7.4

I'm so fond of RR , But in order to keep update , i have to change my rom to Lineage OS.

I have two questions:
1. Should I only use the WinKarbik/android_device_xiaomi_ido to build RR?
2.If not , I want to use Anik1199/android_device_xiaomi_ido instead , Will it work?
How should I do if I want to do this?Need more guidance of this operation.

I've already configured a proper android-rom compile environment.

**Comment by WinKarbik** [comment]
I am already have rr 5.8.1 ans will release it on xda today

**Comment by akhilnarang** [comment]
Don't make issues on github for such stuff, post on G+, or ask your devices devs
